#line 2 "toc_scan.c"

#line 4 "toc_scan.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer toc_yy_create_buffer
#define yy_delete_buffer toc_yy_delete_buffer
#define yy_flex_debug toc_yy_flex_debug
#define yy_init_buffer toc_yy_init_buffer
#define yy_flush_buffer toc_yy_flush_buffer
#define yy_load_buffer_state toc_yy_load_buffer_state
#define yy_switch_to_buffer toc_yy_switch_to_buffer
#define yyin toc_yyin
#define yyleng toc_yyleng
#define yylex toc_yylex
#define yylineno toc_yylineno
#define yyout toc_yyout
#define yyrestart toc_yyrestart
#define yytext toc_yytext
#define yywrap toc_yywrap
#define yyalloc toc_yyalloc
#define yyrealloc toc_yyrealloc
#define yyfree toc_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE toc_yyrestart(toc_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int toc_yyleng;

extern FILE *toc_yyin, *toc_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up toc_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up toc_yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via toc_yyrestart()), so that the user can continue scanning by
	 * just pointing toc_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when toc_yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int toc_yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow toc_yywrap()'s to do buffer switches
 * instead of setting up a fresh toc_yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void toc_yyrestart (FILE *input_file  );
void toc_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE toc_yy_create_buffer (FILE *file,int size  );
void toc_yy_delete_buffer (YY_BUFFER_STATE b  );
void toc_yy_flush_buffer (YY_BUFFER_STATE b  );
void toc_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void toc_yypop_buffer_state (void );

static void toc_yyensure_buffer_stack (void );
static void toc_yy_load_buffer_state (void );
static void toc_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER toc_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE toc_yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE toc_yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE toc_yy_scan_bytes (yyconst char *bytes,int len  );

void *toc_yyalloc (yy_size_t  );
void *toc_yyrealloc (void *,yy_size_t  );
void toc_yyfree (void *  );

#define yy_new_buffer toc_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        toc_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            toc_yy_create_buffer(toc_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        toc_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            toc_yy_create_buffer(toc_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define toc_yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *toc_yyin = NULL, *toc_yyout = NULL;

typedef int yy_state_type;

extern int toc_yylineno;

int toc_yylineno = 1;

extern char *toc_yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr toc_yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up toc_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	toc_yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[518] =
    {   0,
        0,    0,    0,    0,   55,   53,   48,   52,   53,   50,
       53,   49,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   48,   51,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,   48,
        0,    1,    0,    0,   49,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       18,    0,    0,   16,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   48,   51,    2,    2,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    1,
        0,   47,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    0,    0,    0,    0,    0,    0,
        0,   19,    0,    0,   27,   25,    0,    0,    0,   45,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   24,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        0,    8,    0,    4,    0,    0,    0,    0,    0,    0,
       41,   30,    0,    0,    9,   11,    0,    0,    0,    0,
        0,    0,    0,   28,   34,    0,    7,    0,    0,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    0,    0,
        0,    5,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   29,    0,   17,    0,    0,    0,    0,    0,
        0,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    0,    0,    3,    0,   31,    0,
        0,   40,    0,    0,   39,    0,    0,    0,    0,    0,
       23,    0,    0,    0,    0,   44,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,   38,    0,

       37,   26,    0,   33,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    6,    0,
        0,   10,    0,   15,   35,    0,   46,    0,   42,   43,
        0,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    0,    0,    0,    0,   36,    0,
        2,    2,    2,    2,    2,    2,    0,    0,   12,   13,
        0,    0,    0,    2,    2,    2,    2,    2,    2,    2,
        0,   32,    0,   20,    0,    2,    2,    2,    2,    2,
        0,    0,    0,    2,    2,    2,    0,   14,    0,    2,

        2,    2,    0,    0,    2,    2,    0,    0,    2,    2,
        0,   22,    2,    2,   21,    2,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    1,    1,    6,    7,    8,    9,
        7,    7,    7,    7,    7,    7,    7,   10,    1,    1,
        1,    1,    1,    1,   11,    1,   12,   13,   14,   15,
       16,   17,   18,    1,   19,   20,   21,   22,   23,   24,
        1,   25,   26,   27,   28,    1,   29,   30,   31,   32,
        1,   33,    1,    1,   34,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   35,    1,   36,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[37] =
    {   0,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[523] =
    {   0,
        0,   35,   38,   73,  586,  587,  583,  587,   73,  587,
      578,   71,   56,   72,   71,   68,  569,   66,  571,   73,
      558,   76,  551,   75,   82,  555,  564,  101,  587,    0,
      106,    0,  571,  105,   69,  104,  105,  101,  562,   96,
      564,  106,  551,  107,  544,  107,  108,  548,  557,  568,
       95,  587,  131,  566,  133,  543,  554,  539,  531,  122,
      537,  537,  129,  534,  539,  547,  534,  536,  531,  543,
      587,  530,  540,  519,  116,  530,  540,  523,  537,  537,
      524,  534,  520,  148,  587,    0,  150,    0,  153,  156,
      153,  519,  530,  515,  507,  142,  513,  513,  150,  510,

      515,  523,  510,  512,  507,  519,    0,  506,  516,  495,
      147,  506,  516,  499,  513,  513,  500,  510,  496,  141,
      517,  587,  508,  500,  506,  155,  492,  484,  503,  501,
      489,  497,  485,  484,  494,  495,  490,  479,  490,  488,
      153,  477,  487,  486,  483,  473,  477,  462,  483,  460,
      459,  469,  169,  173,  480,  472,  478,  164,  464,  456,
      475,  473,  461,  469,  457,  456,  466,  467,  462,  451,
      462,  460,  162,  449,  459,  458,  455,  445,  449,  434,
      455,  432,  431,  441,  441,  439,  441,  449,  436,  444,
      434,  587,  441,  421,  587,  587,  420,  439,  422,  587,

      423,  439,  176,  426,  437,  433,  435,  423,  410,  414,
      415,  427,  422,  420,  426,  423,  587,  414,  412,  414,
      422,  409,  417,  407,    0,  414,  394,    0,    0,  393,
      412,  395,    0,  396,  412,  184,  399,  410,  406,  408,
      396,  383,  387,  388,  400,  395,  393,  399,  396,    0,
      393,  393,  384,  587,  385,  375,  378,  385,  384,  389,
      587,  587,  389,  383,  364,  363,  371,  371,  373,  364,
      380,  373,  365,  587,  587,  367,  587,  371,  376,  370,
      370,  361,    0,  362,  352,  355,  362,  361,  366,    0,
        0,  366,  360,  341,  340,  348,  348,  350,  341,  357,

      350,  342,    0,    0,  344,    0,  348,  353,  349,  344,
      345,  326,  332,  344,  337,  343,  338,  338,  339,  327,
      173,  330,  587,  326,  587,  335,  326,  329,  331,  334,
      322,  329,  324,  325,  306,  312,  324,  317,  323,  318,
      318,  319,  307,  175,  310,    0,  306,    0,  315,  306,
      309,  311,  314,  302,  298,  302,  587,  291,  587,  295,
      305,  587,  307,  303,  587,  305,  292,  303,  299,  295,
      587,  296,  283,  286,  286,  587,  282,  286,    0,  275,
        0,  279,  289,    0,  291,  287,    0,  289,  276,  287,
      283,  279,    0,  280,  267,  270,  270,    0,  587,  280,

      587,  587,  268,  255,  259,  262,  257,  260,  273,  260,
      268,  186,  259,    0,  269,    0,    0,  257,  244,  248,
      251,  246,  249,  262,  249,  257,  195,  248,  587,  247,
      247,  587,  246,  587,  587,  240,  587,  240,  587,  587,
      250,    0,  241,  241,    0,  240,    0,    0,  234,    0,
      234,    0,    0,  244,  243,  245,  197,  237,  587,  234,
      239,  241,  199,  233,    0,  230,  229,  224,  587,  587,
      226,  220,  211,  224,  219,    0,    0,  221,  206,  196,
      195,  587,  210,  587,  216,  192,    0,  207,    0,  213,
      212,  192,  193,  209,  189,  190,  189,  587,  203,  187,

        0,  201,  200,  194,  198,  192,  191,  178,  181,  174,
      158,  587,  124,    0,  587,    0,  587,  233,  137,  235,
      237,  239
    } ;

static yyconst flex_int16_t yy_def[523] =
    {   0,
      517,    1,  517,    3,  517,  517,  517,  517,  518,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  519,
      520,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  517,
      518,  517,  518,  521,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  519,  520,  519,  520,  522,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,

      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  518,
      521,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  520,  522,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,

      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,

      519,  519,  519,  519,  519,  519,  519,  519,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  517,  517,

      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  517,  517,  517,  517,  517,  517,
      519,  519,  519,  519,  519,  519,  517,  517,  517,  517,
      517,  517,  517,  519,  519,  519,  519,  519,  519,  519,
      517,  517,  517,  517,  517,  519,  519,  519,  519,  519,
      517,  517,  517,  519,  519,  519,  517,  517,  517,  519,

      519,  519,  517,  517,  519,  519,  517,  517,  519,  519,
      517,  517,  519,  519,  517,  519,    0,  517,  517,  517,
      517,  517
    } ;

static yyconst flex_uint16_t yy_nxt[624] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   12,   12,   10,
       13,   14,   15,    6,   16,   17,    6,   18,    6,   19,
       20,   21,    6,   22,   23,   24,   25,   26,    6,    6,
        6,   27,    6,    6,   10,   10,   28,   29,   30,    7,
        8,   31,   32,   33,   34,   34,   34,   32,   35,   36,
       37,   30,   38,   39,   30,   40,   30,   41,   42,   43,
       30,   44,   45,   46,   47,   48,   30,   30,   30,   49,
       30,   30,   32,   32,   28,   29,   52,   55,   55,   55,
       56,   61,   58,   57,   59,   63,   69,   66,   62,   72,
       64,   67,   75,   92,   60,   70,   93,   76,   52,   78,

       73,   77,   84,   85,   79,   53,   80,   51,   51,   88,
       81,   91,   91,   91,   94,   97,   95,  102,   99,  105,
      108,  103,   98,  100,  111,  114,   96,   53,  106,  112,
      115,  109,  116,  113,  120,  143,  117,   86,   89,   55,
       55,   55,  127,  131,   52,  128,  516,  144,  132,   84,
       85,   51,   51,   88,   51,   51,  153,  121,  122,   91,
       91,   91,  159,   53,  163,  160,  175,  188,  205,  164,
       51,   51,   88,   53,  121,  122,  221,  238,  176,  189,
      515,  190,   89,  265,  266,   89,  206,  367,  222,  389,
      223,  294,  295,  439,  440,  239,  514,  368,  513,  390,

      512,   89,  452,  453,  469,  470,  476,  477,  511,  510,
      509,  508,  507,  506,  505,  504,  503,  502,  501,  500,
      499,  498,  497,  496,  495,  494,  493,  492,  491,  490,
      471,  489,  478,   51,   51,   87,   87,  121,  121,  154,
      154,  488,  487,  486,  485,  484,  483,  482,  481,  480,
      479,  475,  474,  473,  472,  468,  467,  466,  465,  464,
      463,  462,  461,  460,  459,  458,  457,  456,  455,  454,
      451,  450,  449,  448,  447,  446,  445,  444,  443,  442,
      441,  438,  437,  436,  435,  434,  433,  432,  431,  430,
      429,  428,  427,  426,  425,  424,  423,  422,  421,  420,

      419,  418,  417,  416,  415,  164,  414,  413,  412,  411,
      410,  409,  408,  407,  406,  405,  404,  403,  402,  401,
      400,  132,  399,  398,  397,  396,  395,  394,  393,  392,
      391,  388,  387,  386,  385,  384,  383,  382,  381,  380,
      379,  378,  377,  376,  375,  374,  373,  372,  371,  370,
      369,  366,  365,  364,  363,  362,  361,  360,  359,  358,
      357,  356,  355,  354,  353,  352,  351,  350,  349,  348,
      347,  346,  345,  344,  343,  342,  341,  340,  339,  338,
      337,  336,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,

      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  293,  292,  291,  290,  289,  288,  287,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  273,  272,  271,  270,  269,  268,  267,  264,
      263,  262,  261,  260,  259,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  225,  224,  220,  219,
      218,  217,  216,  215,  214,  213,  212,  211,  210,  209,

      208,  207,  204,  203,  202,  201,  200,  199,  198,  197,
      196,  195,  194,  193,  192,  191,  187,  186,  185,  122,
      184,  183,  182,  181,  180,  179,  178,  177,  174,  173,
      172,  171,  170,  169,  168,  167,  166,  165,  162,  161,
      158,  157,  156,  155,  152,  151,  150,  149,  148,  147,
      146,  145,  142,  141,  140,  139,  138,  137,  136,  135,
      134,  133,  130,  129,  126,  125,  124,  123,  122,   50,
      119,  118,  110,  107,  104,  101,   90,   83,   82,   74,
       71,   68,   65,   54,   50,  517,    5,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,

      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517
    } ;

static yyconst flex_int16_t yy_chk[624] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    4,    4,    9,   12,   12,   12,
       13,   15,   14,   13,   14,   16,   20,   18,   15,   22,
       16,   18,   24,   35,   14,   20,   35,   24,   51,   25,

       22,   24,   28,   28,   25,    9,   25,   31,   31,   31,
       25,   34,   34,   34,   36,   37,   36,   40,   38,   42,
       44,   40,   37,   38,   46,   47,   36,   51,   42,   46,
       47,   44,   47,   46,   53,   75,   47,  519,   31,   55,
       55,   55,   60,   63,  120,   60,  513,   75,   63,   84,
       84,   87,   87,   87,   89,   89,   89,   90,   90,   91,
       91,   91,   96,   53,   99,   96,  111,  126,  141,   99,
      153,  153,  153,  120,  154,  154,  158,  173,  111,  126,
      511,  126,   87,  203,  203,   89,  141,  321,  158,  344,
      158,  236,  236,  412,  412,  173,  510,  321,  509,  344,

      508,  153,  427,  427,  457,  457,  463,  463,  507,  506,
      505,  504,  503,  502,  500,  499,  497,  496,  495,  494,
      493,  492,  491,  490,  488,  486,  485,  483,  481,  480,
      457,  479,  463,  518,  518,  520,  520,  521,  521,  522,
      522,  478,  475,  474,  473,  472,  471,  468,  467,  466,
      464,  462,  461,  460,  458,  456,  455,  454,  451,  449,
      446,  444,  443,  441,  438,  436,  433,  431,  430,  428,
      426,  425,  424,  423,  422,  421,  420,  419,  418,  415,
      413,  411,  410,  409,  408,  407,  406,  405,  404,  403,
      400,  397,  396,  395,  394,  392,  391,  390,  389,  388,

      386,  385,  383,  382,  380,  378,  377,  375,  374,  373,
      372,  370,  369,  368,  367,  366,  364,  363,  361,  360,
      358,  356,  355,  354,  353,  352,  351,  350,  349,  347,
      345,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  324,
      322,  320,  319,  318,  317,  316,  315,  314,  313,  312,
      311,  310,  309,  308,  307,  305,  302,  301,  300,  299,
      298,  297,  296,  295,  294,  293,  292,  289,  288,  287,
      286,  285,  284,  282,  281,  280,  279,  278,  276,  273,
      272,  271,  270,  269,  268,  267,  266,  265,  264,  263,

      260,  259,  258,  257,  256,  255,  253,  252,  251,  249,
      248,  247,  246,  245,  244,  243,  242,  241,  240,  239,
      238,  237,  235,  234,  232,  231,  230,  227,  226,  224,
      223,  222,  221,  220,  219,  218,  216,  215,  214,  213,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  202,
      201,  199,  198,  197,  194,  193,  191,  190,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  179,  178,
      177,  176,  175,  174,  172,  171,  170,  169,  168,  167,
      166,  165,  164,  163,  162,  161,  160,  159,  157,  156,
      155,  152,  151,  150,  149,  148,  147,  146,  145,  144,

      143,  142,  140,  139,  138,  137,  136,  135,  134,  133,
      132,  131,  130,  129,  128,  127,  125,  124,  123,  121,
      119,  118,  117,  116,  115,  114,  113,  112,  110,  109,
      108,  106,  105,  104,  103,  102,  101,  100,   98,   97,
       95,   94,   93,   92,   83,   82,   81,   80,   79,   78,
       77,   76,   74,   73,   72,   70,   69,   68,   67,   66,
       65,   64,   62,   61,   59,   58,   57,   56,   54,   50,
       49,   48,   45,   43,   41,   39,   33,   27,   26,   23,
       21,   19,   17,   11,    7,    5,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,

      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int toc_yy_flex_debug;
int toc_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *toc_yytext;
#line 1 "toc_scan.l"
#line 2 "toc_scan.l"
/*
 * toc_scan.l -- lexer for toc files
 *
 * Copyright (C) 2004, 2005, 2006, 2007, 2013 Svend Sorensen
 * For license terms, see the file COPYING in this distribution.
 */

#include <stdlib.h>
#include <string.h>

#include "cd.h"
#include "cdtext.h"
#include "toc_parse_prefix.h"
#include "toc_parse.h"

int toc_lineno = 1;

#line 800 "toc_scan.c"

#define INITIAL 0
#define NAME 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int toc_yylex_destroy (void );

int toc_yyget_debug (void );

void toc_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE toc_yyget_extra (void );

void toc_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *toc_yyget_in (void );

void toc_yyset_in  (FILE * _in_str  );

FILE *toc_yyget_out (void );

void toc_yyset_out  (FILE * _out_str  );

			int toc_yyget_leng (void );

char *toc_yyget_text (void );

int toc_yyget_lineno (void );

void toc_yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int toc_yywrap (void );
#else
extern int toc_yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( toc_yytext, (size_t) toc_yyleng, 1, toc_yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( toc_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( toc_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, max_size, toc_yyin))==0 && ferror(toc_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(toc_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int toc_yylex (void);

#define YY_DECL int toc_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after toc_yytext and toc_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( toc_yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(toc_yytext[toc_yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! toc_yyin )
			toc_yyin = stdin;

		if ( ! toc_yyout )
			toc_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			toc_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				toc_yy_create_buffer(toc_yyin,YY_BUF_SIZE );
		}

		toc_yy_load_buffer_state( );
		}

	{
#line 28 "toc_scan.l"


#line 1025 "toc_scan.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of toc_yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 518 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 587 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 30 "toc_scan.l"
{
		yylval.sval = strdup(toc_yytext + 1);
		yylval.sval[strlen(yylval.sval) - 1] = '\0';
		BEGIN(INITIAL);
		return STRING;
		}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 37 "toc_scan.l"
{
		yylval.sval = strdup(toc_yytext);
		BEGIN(INITIAL);
		return STRING;
		}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 43 "toc_scan.l"
{ BEGIN(NAME); return CATALOG; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 45 "toc_scan.l"
{ yylval.ival = MODE_CD_DA; return CD_DA; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "toc_scan.l"
{ yylval.ival = MODE_CD_ROM; return CD_ROM; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 47 "toc_scan.l"
{ yylval.ival = MODE_CD_ROM_XA; return CD_ROM_XA; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 49 "toc_scan.l"
{ return TRACK; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 50 "toc_scan.l"
{ yylval.ival = MODE_AUDIO; return AUDIO; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 51 "toc_scan.l"
{ yylval.ival = MODE_MODE1; return MODE1; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 52 "toc_scan.l"
{ yylval.ival = MODE_MODE1_RAW; return MODE1_RAW; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 53 "toc_scan.l"
{ yylval.ival = MODE_MODE2; return MODE2; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 54 "toc_scan.l"
{ yylval.ival = MODE_MODE2_FORM1; return MODE2_FORM1; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 55 "toc_scan.l"
{ yylval.ival = MODE_MODE2_FORM2; return MODE2_FORM2; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 56 "toc_scan.l"
{ yylval.ival = MODE_MODE2_FORM_MIX; return MODE2_FORM_MIX; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 57 "toc_scan.l"
{ yylval.ival = MODE_MODE2_RAW; return MODE2_RAW; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 58 "toc_scan.l"
{ yylval.ival = SUB_MODE_RW; return RW; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 59 "toc_scan.l"
{ yylval.ival = SUB_MODE_RW_RAW; return RW_RAW; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 61 "toc_scan.l"
{ return NO; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 62 "toc_scan.l"
{ yylval.ival = FLAG_COPY_PERMITTED; return COPY; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 63 "toc_scan.l"
{ yylval.ival = FLAG_PRE_EMPHASIS; return PRE_EMPHASIS; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 64 "toc_scan.l"
{ yylval.ival = FLAG_FOUR_CHANNEL; return FOUR_CHANNEL_AUDIO; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 65 "toc_scan.l"
{ yylval.ival = FLAG_FOUR_CHANNEL; return TWO_CHANNEL_AUDIO; }
	YY_BREAK
/* ISRC is with CD-TEXT items */
case 23:
YY_RULE_SETUP
#line 69 "toc_scan.l"
{ return SILENCE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 70 "toc_scan.l"
{ return ZERO; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 71 "toc_scan.l"
{ BEGIN(NAME); return AUDIOFILE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 72 "toc_scan.l"
{ BEGIN(NAME); return DATAFILE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 73 "toc_scan.l"
{ BEGIN(NAME); return FIFO; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 74 "toc_scan.l"
{ return START; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 75 "toc_scan.l"
{ return PREGAP; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 76 "toc_scan.l"
{ return INDEX; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 78 "toc_scan.l"
{ return CD_TEXT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 79 "toc_scan.l"
{ return LANGUAGE_MAP; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 80 "toc_scan.l"
{ return LANGUAGE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 82 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_TITLE;  return TITLE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 83 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_PERFORMER;  return PERFORMER; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 84 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_SONGWRITER;  return SONGWRITER; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 85 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_COMPOSER;  return COMPOSER; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 86 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_ARRANGER;  return ARRANGER; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 87 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_MESSAGE;  return MESSAGE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 88 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_DISC_ID;  return DISC_ID; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 89 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_GENRE;  return GENRE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 90 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_TOC_INFO1;  return TOC_INFO1; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 91 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_TOC_INFO2;  return TOC_INFO2; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 92 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_UPC_ISRC;  return UPC_EAN; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 93 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_UPC_ISRC;  return ISRC; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 94 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_SIZE_INFO;  return SIZE_INFO; }
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 96 "toc_scan.l"
{ toc_lineno++; /* ignore comments */ }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 97 "toc_scan.l"
{ /* ignore whitespace */ }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 99 "toc_scan.l"
{ yylval.ival = atoi(toc_yytext); return NUMBER; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 100 "toc_scan.l"
{ return toc_yytext[0]; }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 102 "toc_scan.l"
{ toc_lineno++; /* blank line */ }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 103 "toc_scan.l"
{ toc_lineno++; return '\n'; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 104 "toc_scan.l"
{ fprintf(stderr, "bad character '%c'\n", toc_yytext[0]); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 106 "toc_scan.l"
ECHO;
	YY_BREAK
#line 1367 "toc_scan.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(NAME):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed toc_yyin at a new source and called
			 * toc_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = toc_yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( toc_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * toc_yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of toc_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					toc_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			toc_yyrestart(toc_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) toc_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 518 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 518 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 517);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up toc_yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					toc_yyrestart(toc_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( toc_yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve toc_yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void toc_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        toc_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            toc_yy_create_buffer(toc_yyin,YY_BUF_SIZE );
	}

	toc_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	toc_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void toc_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		toc_yypop_buffer_state();
	 *		toc_yypush_buffer_state(new_buffer);
     */
	toc_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	toc_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (toc_yywrap()) processing, but the only time this flag
	 * is looked at is after toc_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void toc_yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	toc_yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE toc_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) toc_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in toc_yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) toc_yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in toc_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	toc_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with toc_yy_create_buffer()
 * 
 */
    void toc_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		toc_yyfree((void *) b->yy_ch_buf  );

	toc_yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a toc_yyrestart() or at EOF.
 */
    static void toc_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	toc_yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then toc_yy_init_buffer was _probably_
     * called from toc_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void toc_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		toc_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void toc_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	toc_yyensure_buffer_stack();

	/* This block is copied from toc_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from toc_yy_switch_to_buffer. */
	toc_yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void toc_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	toc_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		toc_yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void toc_yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)toc_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in toc_yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)toc_yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in toc_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE toc_yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) toc_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in toc_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	toc_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to toc_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       toc_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE toc_yy_scan_string (yyconst char * yystr )
{
    
	return toc_yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to toc_yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE toc_yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) _yybytes_len + 2;
	buf = (char *) toc_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in toc_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = toc_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in toc_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up toc_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		toc_yytext[toc_yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = toc_yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		toc_yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int toc_yyget_lineno  (void)
{
        
    return toc_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *toc_yyget_in  (void)
{
        return toc_yyin;
}

/** Get the output stream.
 * 
 */
FILE *toc_yyget_out  (void)
{
        return toc_yyout;
}

/** Get the length of the current token.
 * 
 */
int toc_yyget_leng  (void)
{
        return toc_yyleng;
}

/** Get the current token.
 * 
 */

char *toc_yyget_text  (void)
{
        return toc_yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void toc_yyset_lineno (int  _line_number )
{
    
    toc_yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see toc_yy_switch_to_buffer
 */
void toc_yyset_in (FILE *  _in_str )
{
        toc_yyin = _in_str ;
}

void toc_yyset_out (FILE *  _out_str )
{
        toc_yyout = _out_str ;
}

int toc_yyget_debug  (void)
{
        return toc_yy_flex_debug;
}

void toc_yyset_debug (int  _bdebug )
{
        toc_yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from toc_yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    toc_yyin = stdin;
    toc_yyout = stdout;
#else
    toc_yyin = NULL;
    toc_yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * toc_yylex_init()
     */
    return 0;
}

/* toc_yylex_destroy is for both reentrant and non-reentrant scanners. */
int toc_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		toc_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		toc_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	toc_yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * toc_yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *toc_yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *toc_yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void toc_yyfree (void * ptr )
{
			free( (char *) ptr );	/* see toc_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 106 "toc_scan.l"



